<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>TeamNexus.Api</AssemblyName>
    <RootNamespace>TeamNexus.Api</RootNamespace>
    <UserSecretsId>f48e714a-f448-41d6-9b66-6e1ac67cc027</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Ai\TeamNexus.Modules.Ai\TeamNexus.Modules.Ai.csproj" />
    <ProjectReference Include="..\Modules\Board\TeamNexus.Modules.Board\TeamNexus.Modules.Board.csproj" />
    <ProjectReference Include="..\Modules\Auth\TeamNexus.Modules.Auth\TeamNexus.Modules.Auth.csproj" />
    <ProjectReference Include="..\Modules\Reporting\TeamNexus.Modules.Reporting\TeamNexus.Modules.Reporting.csproj" />
    <ProjectReference Include="..\Shared\TeamNexus.Shared\TeamNexus.Shared.csproj" />
  </ItemGroup>

</Project>
